FROM ubuntu:22.04

RUN apt-get update -y && apt-get install -y apt-utils && apt-get install -y python3.11 python3-pip

RUN python3.11 -m pip install --upgrade pip

RUN apt-get install -y git

# requirements.txt 복사
COPY requirements.txt /tmp/requirements.txt

# requirements.txt 설치
RUN python3.11 -m pip install -r /tmp/requirements.txt

# app이 돌아갈 폴더 생성
RUN mkdir /app